apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj
spec:
  selector: 
    matchLabels:
      app: rashed
  replicas: 3
  template: 
    metadata:
      name: my-first-pod
      labels: 
        app: rashed
    spec:          
      containers:
        - image: rashed978/project
          name: project-container
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "512Mi"